//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteId { get; set; }
        public Nullable<int> ProfessorId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<short> Grade { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
