//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectProfessor
    {
        public int ProfessorSubjectid { get; set; }
        public int Subjectid { get; set; }
        public int Professorid { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
